### ISSUE TITLE
Add to the readme instruction for csvtoterms

### ISSUE THREAD

**Issue by Mte90** [Mte90/SyntaxAlert#12]
With a bit of docs about the csv structure.

**Comment by rubiagatra** [comment]
I am interested with this one! @Mte90

**Comment by Mte90** [comment]
The issue is yours if you are fast! As I can see people do stuff also if someone want to work on that.

**Comment by nikhilkumarsingh** [comment]
Check out #18

**Comment by rubiagatra** [comment]
I fixed a bug and updated readme in #19
